name: jeblarrr
description: "A new Flutter project for JEBLARR Mie Jebew."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Tambahkan library ini untuk fungsi telepon/WhatsApp
  url_launcher: ^6.3.2 
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/anu_1.jpg
    - assets/images/anu_2.jpg
    - assets/images/mi_jebew_1.jpg
    - assets/images/mi_jebew_2.jpg
    - assets/images/mi_jebew_3.jpg
    - assets/images/mi_jebew_4.jpg
    - assets/images/mi_jebew_5.jpg
    - assets/images/mi_jebew_6.jpg
    - assets/images/aku.png
    - assets/images/dava.png
    - assets/images/nopal_y.png
    - assets/images/logo_jeblarrr.png
    